### PR TITLE
Hello trying to Pull (:

### PR DESCRIPTION
**Pull request by Gaabimoreno**
Accept this shit

### CODE REVIEW

**Comment by sleipnir** [comment]
Corrija a sua grafia

**Comment by Gaabimoreno** [comment]
Nop. Just accept this. then I pay you a coffe 💅

**Comment by sleipnir** [comment]
Ai que medo

**Comment by sleipnir** [comment]
so terrible

**Comment by Gaabimoreno** [comment]
Dont be afraid. It's for a good reason 🍂

**Comment by sleipnir** [comment]
maybe

**Comment by Gaabimoreno** [comment]
🌮

**Comment by sleipnir** [comment]
👍

**Pull request merged**
